[package]
name = "syncrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.11.3"
serde = "1.0.160"
vizia = { git = "https://github.com/vizia/vizia.git", features = ["serde"] }
